config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :hiyos, except: [:show] do
    collection do
      post :confirm
    end
  end
  
  root 'hiyos#index'
  

end

app/models/hiyo.rb
class Hiyo < ActiveRecord::Base
    validates :content, length: { in: 1..255 }
    belongs_to :user
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :hiyos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_actionでdeviseのストロングパラメーターにnameカラムを追加するメソッドを実行します。
  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = %i(name)

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/hiyos_controller.rb
class HiyosController < ApplicationController
  before_action :set_hiyo, only: [:edit,:update,:destroy]
  #before_action :authenticate_user!
  
  def index
    @hiyo = Hiyo.new
    @hiyos = Hiyo.all
  end
  
  def create
    @hiyo = Hiyo.new(hiyos_params)
    @hiyo.user_id = current_user.id
    if @hiyo.save
      redirect_to hiyos_path, notice: "ひよった！"
    else
      render action: "new"
    end
  end

  def new
    if params[:back]
      @hiyo = Hiyo.new(hiyos_params)
    else
      @hiyo = Hiyo.new
    end
  end
  
  def edit
  end
  
  def update
    @hiyo.update(hiyos_params)
    redirect_to hiyos_path, notice: "ひよりなおした！"
  end
  
  def destroy
    @hiyo.destroy
    redirect_to hiyos_path, notice: "ひよってなんかいなかった！"
  end
  
  def confirm
    @hiyo = Hiyo.new(hiyos_params)
    render :new if @hiyo.invalid? 
  end

  private
  
  def hiyos_params
    params.require(:hiyo).permit(:content)
  end
  
  def set_hiyo
    @hiyo = Hiyo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hiyos_helper.rb
module HiyosHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
        confirm_hiyos_path
        elsif action_name == 'edit'
        hiyo_path
        end
    end
end

app/helpers/hiyotter_helper.rb
module HiyotterHelper
end

app/helpers/hiyotters_helper.rb
module HiyottersHelper
end

app/views/hiyos/_form.html.erb
<section class=form_hiyo>
  <%= form_for(@hiyo, url: choose_new_or_edit) do |f| %>
    
    <% if @hiyo.errors.any? %>
        <div id="error_explanation">
          <h2><%= @hiyo.errors.count %>こ、ひよりなおして。</h2>
          <ul>
          <% @hiyo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
    <% end %>
    
    <%= f.text_field :content, class: 'form-control' %>
    <br>
    <%= f.submit "ひよる！", class: 'btn btn-warning btn-block' %>
    
  <% end %>

  <%= link_to "ひよりのまとめへ", hiyos_path, class: "btn btn-default btn-block" %>
  
</section>

app/views/hiyos/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>これでひよる？</h2>

    <%= form_for(@hiyo) do |f| %>
      <%= f.hidden_field :content %>
      <h4><%= @hiyo.content %><h4>
      <%= f.submit "ひよる！", class: 'btn btn-warning btn-block' %>
    <% end %>

    <%= form_for(@hiyo, url: new_hiyo_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name:"back", class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/hiyos/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>ひよりなおす</h2>
        <%= render "form" %>
    </div>
</div>

app/views/hiyos/index.html.erb
<section class=notice_hiyo>
    <h3 class="flash"><%= notice %><%= alert %><h3>
</section>

<body>
    
    <div class="container">
        <div class="row">
            <%= form_for(@hiyo) do |f| %>
                <div class="col-xs-12 col-sm-12 col-md-7 col-md-offset-2">
                    <%= f.text_field :content,class: "form-control" %>
                </div>
                <div class="col-xs-offset-9">
                    <%= f.submit "ひよる！", class: "btn btn-default btn-sm btn-warning" %>
                </div>
            <% end %>
        </div>
    </div>

    <section class=list_hiyo>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
                    <% @hiyos.each do |hiyo| %>
                        <p><%= hiyo.content %></p>
                        <div class="btn-group col-xs-offset-9">
                            <button type="button" class="btn btn-sm btn-warning ">ひよ</button>
                            <button type="button" class="btn btn-sm btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><%= link_to "りなおす！", edit_hiyo_path(hiyo.id), class: "btn btn-default btn-xs btn-warning" %></li>
                                <li><%= link_to "ってなんかいなかった！", hiyo_path(hiyo.id), method: :delete, data: { confirm: 'そういうことにします？'}, class: "btn btn-default btn-xs" %></li>
                            </ul>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </section>
</body>

app/views/hiyos/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>ひよる！</h2>
        <%= render "form" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ひよぐらむ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-default">
    <ul class="header_left">
      <li><%= link_to "ひよりのまとめ", hiyos_path %></li>
    </ul>
    <% if user_signed_in? %>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path %></li>
      <li><%= link_to 'サインアップ', new_user_registration_path %></li>
    <% end %>
    <ul class="header_right">
      <li><%= link_to "ひよる！", new_hiyo_path %></li>
    </ul>
      
  </nav>  

<%= yield %>

</body>
</html>